/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreNosRouteImport } from './routes/sobre-nos'
import { Route as OQueFazemosRouteImport } from './routes/o-que-fazemos'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as ComoAjudarRouteImport } from './routes/como-ajudar'
import { Route as AdotarRouteImport } from './routes/adotar'
import { Route as IndexRouteImport } from './routes/index'

const SobreNosRoute = SobreNosRouteImport.update({
  id: '/sobre-nos',
  path: '/sobre-nos',
  getParentRoute: () => rootRouteImport,
} as any)
const OQueFazemosRoute = OQueFazemosRouteImport.update({
  id: '/o-que-fazemos',
  path: '/o-que-fazemos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoAjudarRoute = ComoAjudarRouteImport.update({
  id: '/como-ajudar',
  path: '/como-ajudar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdotarRoute = AdotarRouteImport.update({
  id: '/adotar',
  path: '/adotar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adotar': typeof AdotarRoute
  '/como-ajudar': typeof ComoAjudarRoute
  '/contactos': typeof ContactosRoute
  '/o-que-fazemos': typeof OQueFazemosRoute
  '/sobre-nos': typeof SobreNosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adotar': typeof AdotarRoute
  '/como-ajudar': typeof ComoAjudarRoute
  '/contactos': typeof ContactosRoute
  '/o-que-fazemos': typeof OQueFazemosRoute
  '/sobre-nos': typeof SobreNosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adotar': typeof AdotarRoute
  '/como-ajudar': typeof ComoAjudarRoute
  '/contactos': typeof ContactosRoute
  '/o-que-fazemos': typeof OQueFazemosRoute
  '/sobre-nos': typeof SobreNosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adotar'
    | '/como-ajudar'
    | '/contactos'
    | '/o-que-fazemos'
    | '/sobre-nos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adotar'
    | '/como-ajudar'
    | '/contactos'
    | '/o-que-fazemos'
    | '/sobre-nos'
  id:
    | '__root__'
    | '/'
    | '/adotar'
    | '/como-ajudar'
    | '/contactos'
    | '/o-que-fazemos'
    | '/sobre-nos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdotarRoute: typeof AdotarRoute
  ComoAjudarRoute: typeof ComoAjudarRoute
  ContactosRoute: typeof ContactosRoute
  OQueFazemosRoute: typeof OQueFazemosRoute
  SobreNosRoute: typeof SobreNosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-nos': {
      id: '/sobre-nos'
      path: '/sobre-nos'
      fullPath: '/sobre-nos'
      preLoaderRoute: typeof SobreNosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-que-fazemos': {
      id: '/o-que-fazemos'
      path: '/o-que-fazemos'
      fullPath: '/o-que-fazemos'
      preLoaderRoute: typeof OQueFazemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-ajudar': {
      id: '/como-ajudar'
      path: '/como-ajudar'
      fullPath: '/como-ajudar'
      preLoaderRoute: typeof ComoAjudarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adotar': {
      id: '/adotar'
      path: '/adotar'
      fullPath: '/adotar'
      preLoaderRoute: typeof AdotarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdotarRoute: AdotarRoute,
  ComoAjudarRoute: ComoAjudarRoute,
  ContactosRoute: ContactosRoute,
  OQueFazemosRoute: OQueFazemosRoute,
  SobreNosRoute: SobreNosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
